language: julia
os:
  - osx
  - linux
julia:
  - 0.4
  - 0.5
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd());'
#  - julia -e 'ENV["MADS_NO_PYTHON"]=""; ENV["MADS_NO_PLOT"]=""; Pkg.build("Mads"); reload("Mads"); Mads.checkout(false); Pkg.test("Mads"; coverage=true)'
  - julia -e 'ENV["MADS_TRAVIS"]=""; Pkg.build("Emcee"); Pkg.test("Emcee"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Emcee")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'